spring.application.name=college-space-backend
server.port=8080

# Database Configuration (MySQL example, change driver for Postgres if needed)
spring.datasource.url=jdbc:mysql://localhost:3306/collegespace?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Pvl@@@1985
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Allow React frontend to connect
spring.mvc.cors.allowed-origins=http://localhost:5173
